version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - restore_cache:
          keys:
          - composer-v1-{{ checksum "composer.lock" }}
          - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: ./vendor/bin/phpunit tests --log-junit tests/test_results.xml
      - store_test_results:
          path: tests/test_results.xml
      - store_artifacts:
          path: tests/test_results.xml

workflows:
  version: 2
  workflow:
    jobs:
    - build_and_test